/*
 * PioneerServerAboutBox.java
 */

package pioneerserver;

import javax.swing.JOptionPane;
import org.jdesktop.application.Action;

public class SetServer extends javax.swing.JDialog {
          
    public SetServer(java.awt.Frame parent) {
        super(parent);
        initComponents();
        getRootPane().setDefaultButton(jButton1);
        //onemoguciti button apply
        jButton3.setEnabled(false);
    }
    //Ako je pritisnuto Cancel zatvoriti formu
    @Action
    public void closeAboutBox() {
        setVisible(false);
    }
    //Ako je pritisnuto OK
    @Action
    public void setServer(){
        try{
            //Upisuje se adresa servera
            GlobalVariables.ServerAddress=this.jTextField1.getText();
            //U privremenu varijablu se smjesta vrjednost socket porta
            String temp=this.jTextField2.getText();
            //Upisuje se soket port
            GlobalVariables.socketPort=Integer.parseInt(temp);
            //zatvara forma
            closeAboutBox();
            //Omogucuje se menuItem za konekciju
            PioneerServerApp.Instance.jMenuItem1.setEnabled(true);
            //Omogucuje se panel http://
            PioneerServerApp.Instance.jMenuItem4.setEnabled(true);
        }catch(NumberFormatException ex){
            Log.getInstance().write("ERROR SetServer 1: "+ex);
            JOptionPane.showMessageDialog(this, "Wrong socket port!","Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    //Pritisak na dugme Apply
    @Action
    public void applyServer(){
        try{
            //Uzima se adresa servera
            GlobalVariables.ServerAddress=this.jTextField1.getText();
            String temp=this.jTextField2.getText();
            //Broj socket porta
            GlobalVariables.socketPort=Integer.parseInt(temp);
            //onemogucuje se dugme Apply
            this.jButton3.setEnabled(false);
            //Omogucuje se konekcija i pristup http serveru
            PioneerServerApp.Instance.jMenuItem1.setEnabled(true);
            PioneerServerApp.Instance.jMenuItem4.setEnabled(true);
        }catch(NumberFormatException ex){
            Log.getInstance().write("ERROR SetServer 2: "+ex);
            JOptionPane.showMessageDialog(this, "Wrong socket port!","Error", JOptionPane.ERROR_MESSAGE);
        }
    }
   //Promjena servera ili socket porta omogucuje dugme Apply 
   @Action
   public void change(){
       this.jButton3.setEnabled(true);
   }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pioneerserver.PioneerServerApp.class).getContext().getResourceMap(SetServer.class);
        setTitle(resourceMap.getString("aboutBox.title")); // NOI18N
        setName("aboutBox"); // NOI18N
        setResizable(false);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(pioneerserver.PioneerServerApp.class).getContext().getActionMap(SetServer.class, this);
        jButton1.setAction(actionMap.get("setServer")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(65, 23));

        jButton2.setAction(actionMap.get("closeAboutBox")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jButton3.setAction(actionMap.get("applyServer")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.setPreferredSize(new java.awt.Dimension(65, 23));

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setAction(actionMap.get("change")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N
        jTextField1.setNextFocusableComponent(jTextField2);

        jTextField2.setText(resourceMap.getString("jTextField2.text")); // NOI18N
        jTextField2.setAction(actionMap.get("change")); // NOI18N
        jTextField2.setName("jTextField2"); // NOI18N
        jTextField2.setNextFocusableComponent(jButton1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(18, 18, 18)
                        .add(jTextField1))
                    .add(layout.createSequentialGroup()
                        .add(jLabel3)
                        .add(18, 18, 18)
                        .add(jTextField2))
                    .add(layout.createSequentialGroup()
                        .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
   
}